[[layers]]
  name = "lang#python"
  format_on_save = 1
  python_file_head = [
    '#!/usr/bin/python3',
    '# -*- coding: utf-8 -*-',
    '# @Author: Wiley<throughskybrim@gmail.com>',
    '',
    '',
  ]

[[layers]]
  name = "format"

[[layers]]
  name = "debug"